### PR TITLE
Bugfix #10 - Support missing spark_options from pytest.ini

### PR DESCRIPTION
**Pull request by skyegecko**
Hi,

This PR includes a test-case and fix for #10. It depends on #11.

### CODE REVIEW

**Comment by malexer** [comment]
@dutchgecko have introduced some changes, please review

**Comment by malexer** [comment]
still need to deal with Travis config, will do it later

**Comment by skyegecko** [comment]
The tox config is obviously better, so that's fine.

Your version in 2ef93f4 gives a smaller diff (no changes to `pytest_spark/__init__.py `) and doesn't need to defensively `raise` like I added, but will mean that `initialize()` can be called from different locations. I've got no problems with this, and it's your project so you can arrange the code as you like, just pointing out the tradeoff.

**Comment by malexer** [comment]
>will mean that initialize() can be called from different locations

yep, idea was to have SparkConfigBuilder as a singleton

**Comment by malexer** [comment]
Released in 0.5.2. Please find it on pypi

**Pull request merged**
